version: '3'
services:
  walkie:
    build: .
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web
    environment:
      NODE_ENV: production
      TZ: America/Bogota
      VIRTUAL_HOST: walkie.lumisar.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: walkie.lumisar.com
      LETSENCRYPT_EMAIL: danielsarmientoenterprise@gmail.com

networks:
  web:
    external: true